# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # makes classes these folders available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/App/*'

    # controllers are imported separately to make sure they
    # have the tag that allows actions to type-hint services
    App\Controller\:
        resource: '../src/App/Controller'
        tags: ['controller.service_arguments']

    Obokaman\StockForecast\:
        resource: '../src/StockForecast/*'

    # Define an alias for this interface, so we can take profit of autowire to change the
    # implementation we want to use for the prediction strategy.
    #Obokaman\StockForecast\Domain\Service\Predict\PredictionStrategy: '@Obokaman\StockForecast\Domain\Service\Predict\Strategy\CumulativeMovingAverage'
    Obokaman\StockForecast\Domain\Service\Predict\PredictionStrategy: '@Obokaman\StockForecast\Infrastructure\MachineLearning\PhpMl\LeastSquares'
    #Obokaman\StockForecast\Domain\Service\Predict\PredictionStrategy: '@Obokaman\StockForecast\Infrastructure\MachineLearning\PhpMl\SupportVectorRegression'


